In [1]:
import pandas
from Functions import scale, getStationary
import numpy as np

def clear():
  import os
  import re
  directory = '../data/'
  files = os.listdir(directory)
  files_to_delete = [file for file in files if re.search(r'-', file)]
  for file_to_delete in files_to_delete:
    os.remove(os.path.join(directory, file_to_delete))

def print_stats(df):
  for column in df.columns:
    min_value = df[column].min()
    max_value = df[column].max()
    avg_value = df[column].mean()
    has_nan = df[column].isna().any()
    print(f"Column '{column}': Min = {min_value}, Max = {max_value}, Mean = {avg_value}", {has_nan})

In [3]:
fn = 'bnb21'
dat = ((pandas.read_csv(f'../data/{fn}.csv',sep=',')).sort_values('date')[['date','open','high','low','close','volume']]).set_index('date')

try:
  dat_test = ((pandas.read_csv(f'../data/{fn}-full.csv',sep=',')).sort_values('date')[['date','close_over_low','delta','amplitude','volume']]).set_index('date')
except:
  pass

# clear()
getStationary(dat, fn, True)
# print_stats(dat_test)

                        close    volume     delta  amplitude  close_over_low
date
2021-01-01 00:00:00   37.4160 -0.134153 -0.082354  -0.990103       -0.987673
2021-01-01 00:01:00   37.4362  0.096420 -0.079303  -0.980100       -0.983159
2021-01-01 00:02:00   37.3969  0.220048 -0.099538  -0.976573       -0.984758
2021-01-01 00:03:00   37.3398  0.140998 -0.098566  -0.986393       -1.000000
2021-01-01 00:04:00   37.3314  0.028148 -0.085876  -0.987233       -0.991692
...                       ...       ...       ...        ...             ...
2021-12-31 23:55:00  511.6000 -0.197631 -0.083648  -0.997787       -1.000000
2021-12-31 23:56:00  511.6000 -0.110410 -0.081222  -0.991149       -0.996064
2021-12-31 23:57:00  511.8000 -0.326386 -0.078796  -0.993363       -0.992130
2021-12-31 23:58:00  511.3000  0.007666 -0.093356  -0.977852       -0.976359
2021-12-31 23:59:00  511.4000 -0.255039 -0.078792  -0.986719       -0.992124

[524607 rows x 5 columns]